name: FP_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.12
  - pip=25.0.1
  - jupyterlab=4.4.2
  - pip:
      - SQLAlchemy==2.0.41
      - black==25.1.0
      - coloredlogs==15.0.1
      - matplotlib==3.10.1
      - mpld3==0.5.10
      - notebook==7.4.2
      - numpy==2.2.6
      - pandas==2.2.3
      - prettytable==3.16.0
      - prophet==1.1.7
      - pydub==0.25.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - snakeviz==2.2.2
      - streamlit==1.45.1
      - sympy==1.14.0
      - tqdm==4.67.1
      - typeguard==4.4.2